### ISSUE TITLE
Criar Navbar

### ISSUE THREAD

**Issue by Rafarache** [Rafarache/ReactNativeApp#14]
Criar uma maneira de navegar entre seções/abas/telas

### Reference:

https://usabilitygeek.com/app-navigation-design-mistakes/

![image](https://user-images.githubusercontent.com/47155967/81518008-0a9dd900-9313-11ea-9342-750e8f57583a.png)

**Comment by MatheusHiro** [comment]
que abas e telas tem no app?

**Comment by Rafarache** [comment]
tem duas telas, a das tarefas e a de inserir tarefas ( elas ficam juntas )

**Comment by Rafarache** [comment]
93625c2cdcc5ac1d507d0fdfecd809d5065e1cba
